---
- name: Install
  become: true
  ansible.builtin.apt:
    # https://www.synology.com/en-global/support/download/DS723+?version=7.1#utilities
    deb: "https://global.synologydownload.com/download/Utility/SynologyDriveClient/{{ _version }}-{{ _build }}/Ubuntu/Installer/synology-drive-client-{{ _build }}.x86_64.deb"
